### PR TITLE
Add support for Image SEO module

### LINKED ISSUE #3146: New Feature - Image SEO module
Just creating an issue here so I can it reference it when adding the code that has to go in free for this.

### PR DESCRIPTION
**Pull request by arnaudbroes**
Resolves #3146

## Proposed changes

This PR adds the code that has to go in free to support the Image SEO module.

As an extra, I've fixed the flags on the Feature Manager screen and added CTA buttons to upgrade to the premium version - 

image

## Types of changes

- New feature (non-breaking change which adds functionality)
- Improves existing functionality

## Checklist

- [x] I've selected the appropriate branch (ie x.y rather than master).
- [x] I've created an appropriate title, descriptive of what the PR does.
- [ ] Travis-ci runs with no errors.

## Testing instructions

This has to be tested after it's built as Pro (see PR in Pro repo) but also as the free version:

1. Install the PR and go to the Feature Manager screen. 
There should be no notices and the Video Sitemap module and Image SEO module should have two orange CTA buttons. The flags should both say "PRO".
2. Check the link for both of the upgrade buttons. The structure should be the same except for the "utm_content" param which should be different and state the name of the module.
3. Check that plugin doesn't throw any errors when the Image SEO module is activated in Pro, and when you then deactivate Pro and activate the free version. Same goes for the Video Sitemap module.

### CODE REVIEW

**Comment by arnaudbroes** [comment]
@wpsmort I'm closing https://github.com/awesomemotive/aioseop-pro/issues/79 since I fixed it in this PR.

**Comment by wpsmort** [comment]
This is tested and is good.

**Comment by arnaudbroes** [comment]
@wpsmort I'm going to send this back to development just for now since the help text will need to be updated here for the changes we discussed tonight.

**Comment by arnaudbroes** [comment]
@wpsmort This can be tested again. See (3) for an additional testing instruction.

**Pull request closed without merging**
