### PR TITLE
Add aioseop_attachment_size filter to all image settings

### PR DESCRIPTION
**Pull request by OlegApanovich**
…ta module (#2080)

Issue #2080 

## Proposed changes

Extend aioseop_attachment_size filter to other image options in social meta module.

## Types of changes

What types of changes does your code introduce?
_Delete those that don't apply_

- Bugfix (non-breaking change which fixes an issue)
- Improves existing functionality
- Improves existing code

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code. If creating a separate issue for an item, link to the issue # at the end of the line._

- [x ] I've selected the appropriate branch (ie x.y rather than master).
- [x] I've created an appropriate title, descriptive of what the PR does.
- [ ] Travis-ci runs with no errors.
- [ ] I have added tests that prove my fix is effective/my feature works or have created an issue for it (if appropriate).
- [ ] I have added necessary documentation, or have created an issue for docs (if appropriate).

### CODE REVIEW

**Comment by michaeltorbert** [comment]
Maybe I'm missing something but this seems to do nothing other than remove our own API filter hooks.

**Comment by OlegApanovich** [comment]
It is not removing filter hooks @michaeltorbert It is replaced them to another location where they can cover all image settings of "Select OG:Image Source" options. Right now filter work only for a 'first attached image' option, but after I replaced filter to another location and add additinal function filter began to work to other options too.
In comment to issue @wpsmort sayed "By following these steps above, you'll see that the only images affected by the filter are the first attached image and the first image in content. The filter needs to also affect the default image, featured image and first available image." I think he said it because thought it difficult to extend filter to options that parse the content searching img tag. But my PR cover all possible setting options

**Comment by michaeltorbert** [comment]
@OlegApanovich Yes, I hadn't seen the second file, which is why I already deleted my comment.

**Comment by EkoJR** [comment]
In the past, we've experience performance issues with converting attachment urls to post ids, and there's been a few related issues concerning how attachment urls operate. There's a function that is already available that serves the same purpose as your `aioseop_get_attachment_id( $url )` in the most optimal way that was found possible.

It is `aiosp_common::attachment_url_to_postid( $url )` in `inc/aiosp_common.php`.

Looking at your query_args, I believe that was one of the queries I had tested. Unfortunately, using any meta query search with attachments has big impact on large sites.

**Comment by OlegApanovich** [comment]
@EkoJR  in my last commit I replace my new function with aiosp_common::attachment_url_to_postid( $url )
Also I improve it trying to escape performance issue that function produce on large sites.
I test it on a 20k post wordpress installation and existing call of this function in
AIOSEOP_Graph_Organization::get_logo_id() has huge improvement in a first invocation when cash and transient data do not exist yet. I add some benchmarks in attached files.
Screenshot from 2019-11-08 10-00-29
Screenshot from 2019-11-08 10-07-00

**Comment by arnaudbroes** [comment]
@EkoJR let me know what your thoughts are on this. I believe you were still reluctant on approving this.

**Comment by EkoJR** [comment]
I did a comparison on the benchmarks, and it seems like that the changes added degrades the performance. The initial load is the main concern (without being able to use transient data), and found that the Time is nearly doubled and the Memory increases by a good margin.

Originally, the code was designed to resolve user reports with timeout errors. At the time, it was only the Sitemap that would use the function, and it still heavily relies on it; it's also what I used to test on. I had also found any meta_query would significantly degrade performance, which I had mentioned as well.

The 2nd query I haven't fully tested yet, but seems interesting. It's still heavier than query_1, but I need to load a site with more edited images in use (it was only called twice on current benchmarks), and compare benchmarks with the code that was commented out. As a public release, query_2 should remain disabled though.

## Total Time/Memory

The initial load times seem to be...

Time: 91.19% (degrade) increase.
Memory: 11.95% (degrade) increase.

### Parent/Base Commit

Time | Memory
---- | ------
67,511,710 | 1,239,914,456 
66,606,753 | 1,236,776,296

### PR

Time | Memory
---- | ------
129,073,847 | 1,388,032,088
66,911,419 | 1,236,918,992

## Screenshots

### Parent/Base Commit

#### Initial Load

Master 01 Time
Master 01 Memory

#### Reload (2nd load)

Master 02 Time
Master 02 Memory

### PR Branch

#### Initial Load

PR 01 Time
PR 01 Memory

#### Reload (2nd load)

PR 02 Time
PR 02 Memory

**Comment by OlegApanovich** [comment]
Yes @EkoJR  there defenetely some perfomence degradetion in All_in_One_SEO_Pack_Sitemap::get_images_from_post() in my previos commit I do not paid attention on it and I try to improve it in my last commit that I added today.

In our benchmarks key function right now is aiosp_common::set_transient_url_postids()  that has heavy database query that load all url for all existent attachments in one array.
Right now we use aiosp_common::set_transient_url_postids() function in 2 places:
1. All_in_One_SEO_Pack_Sitemap::get_images_from_post()
2. AIOSEOP_Graph_Organization::get_logo_id()

And in my first commit I add use of aiosp_common::set_transient_url_postids() in third place to resolve initial issue for I created it pull requers.
3. All_in_One_SEO_Pack_Opengraph::add_meta()

Right now I think we already use aiosp_common::set_transient_url_postids() function improperly cos we have two different task when we use in
1. All_in_One_SEO_Pack_Sitemap::get_images_from_post()
2. AIOSEOP_Graph_Organization::get_logo_id()

In our first place with sitemap we have mass action when we need all urls and in a second place with social media we need only one url to convert to id.
I think it is too expensive to load all attachment urls in one query even with static cache and transient functionality in later use.
I think we must divide using aiosp_common::set_transient_url_postids() function on two separate 
1. aiosp_common::convert_image_url_to_id_bulky()
2.aiosp_common::convert_image_url_to_id_individually()

Firt we will use for a single url to id attchment query and second for a multiple url to id attchment query and we must add optionality to function that will be determine 1 or 2 query use for this task ( first query for manin images, second query for custom sizes )

All of it I already implemented in my last commit.
Below I had some benchmarks that demonstrate performance improvement especially for already existing AIOSEOP_Graph Organization::get_logo_id() function.


All_in_One_SEO_Pack_Sitemap::get_images_from_post() - **master branch**
**Initial Load**
master-sitemap

All_in_One_SEO_Pack_Sitemap::get_images_from_post() - **pr branch**
**Initial Load 1 query**
branch-1query-sitemap

All_in_One_SEO_Pack_Sitemap::get_images_from_post() - **pr branch**
**Initial Load 2 query**

branch-2query-sitemap

AIOSEOP_Graph_Organization::get_logo_id() - **master branch**
**Initial Load**

opengraph-initload-master

AIOSEOP_Graph_Organization::get_logo_id() - **pr branch**
**Initial Load**

opengraph-initload-branch

Even if you think that use second query in sitemap case is not rational we can deactivate it just set second option to false. Right now in my last commit I set it as true.

Please review my pr with my last commit again.

**Comment by arnaudbroes** [comment]
@OlegApanovich I'm going to close your PR for now because we're currently in the midst of cleaning up things and we'll probably revisit the Social Meta module in its entirety in the near future, but it's linked to the issue so we'll definitely have a look at this again when we get to it.

**Pull request closed without merging**
