### PR TITLE
Fix PHP error trying to get property 'ID' from object

### PR DESCRIPTION
**Pull request by EkoJR**
Issue #2368

## Proposed changes

Describe the big picture of your changes here to communicate why the PR should be accepted. If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Types of changes

What types of changes does your code introduce?

- Bugfix (non-breaking change which fixes an issue)
- Improves existing functionality
- Improves existing code

## Checklist

- [x] I've selected the appropriate branch (ie x.y rather than master).
- [x] I've created an appropriate title, descriptive of what the PR does.
- [x] Travis-ci runs with no errors.
- [ ] I have added tests that prove my fix is effective/my feature works or have created an issue for it (if appropriate).
- [ ] I have added necessary documentation, or have created an issue for docs (if appropriate).

## Testing instructions

1. Install Pro on a new site
2. Go to the General Settings screen and check the box for Categories under SEO on only these taxonomies
3. Activate the Social Meta module and go to the Social Meta settings 
4. Select First Attached Image in the Select OG:Image Source dropdown  
5. Create an empty category and then view the category and you should see the PHP Notice

### CODE REVIEW

**Comment by arnaudbroes** [comment]
@EkoJR still in development?

**Comment by EkoJR** [comment]
@arnaudbroes No, it's not In-Development. I was waiting on travis to finish up before I assigned someone else, and forgot to switch it.

**Comment by wpsmort** [comment]
@EkoJR Can you also fix the related PHP notice below that shows if you select either First Image in Content or First Available Image in Image Settings for the Social Settings module.

Trying to get property 'ID' of non-object in all-in-one-seo-pack-i-2368/admin/aioseop_module_class.php on line 1993

**Comment by EkoJR** [comment]
@wpsmort Nice catch btw. I had tested against the one setting thinking it was just the 1 function.

**Comment by wpsmort** [comment]
This is tested and is good.

**Comment by arnaudbroes** [comment]
This is good. Merging and closing the issue.

**Pull request merged**
