### PR TITLE
Security and performance improvement: rel="noopener noreferrer"

### PR DESCRIPTION
**Pull request by netchild**
## Proposed changes

For all external href with target="_blank" to add
rel="noopener noreferrer". The reason for this patch is performance
and security, you can find more info at
    https://developers.google.com/web/tools/lighthouse/audits/noopener
and
    https://jakearchibald.com/2016/performance-benefits-of-rel-noopener/

## Types of changes

What types of changes does your code introduce?

- Improves existing functionality
- Improves existing code

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code. If creating a separate issue for an item, link to the issue # at the end of the line._

- [ ] I've selected the appropriate branch (ie x.y rather than master).
- [X] I've created an appropriate title, descriptive of what the PR does.
- [X] If I added, removed or modified any translatable strings, I updated the commonstrings.php file (free repository) accordingly or else opened an issue for it.
- [ ] I have added tests that prove my fix is effective/my feature works or have created an issue for it (if appropriate).
- [ ] I have added necessary documentation, or have created an issue for docs (if appropriate).

### CODE REVIEW

**Comment by wpsmort** [comment]
I'm closing this PR because WordPress already adds the noopener and noreferrer attributes to all external links.

**Comment by netchild** [comment]
Can you please provide a reference to wordpress docs or whatever which suggests this is the case? If I look at the source code of the admin page of the plugin in my WP-instance, I see no such behavior:
`<li><a href='https://semperplugins.com/all-in-one-seo-pack-pro-version/?utm_source=WordPress&utm_campaign=liteplugin&utm_medium=admin-menu'><span class='upgrade_menu_link'>Upgrade to Pro</span></a></li></ul></li>`

I also see no such behavior on all my external links in a blog post.

**Comment by wpsmort** [comment]
It was added in this Trac ticket - https://core.trac.wordpress.org/ticket/37941
Here's the function doc - https://developer.wordpress.org/reference/functions/wp_targeted_link_rel/

**Comment by netchild** [comment]
Thanks for the reference, but as you can see in my example from above, the output of a real instance as it arrives in the browser is different. In the example we have target=_blank, but no rel="noopener noreferrer". The WP instance I used to get this example is the most recent released WP version and the most recent released all-in-one-seo-pack plugin without modifications. So the link to the pro-version is not having the properties you suggest it should have.

**Pull request closed without merging**
